Nature_Shot/Web/NatureShot.Web/Controllers/ImagesController.cs
namespace NatureShot.Web.Controllers
{
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.IO;
    using System.Linq;
    using System.Threading.Tasks;

    using CloudinaryDotNet;
    using CloudinaryDotNet.Actions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using NatureShot.Data;
    using NatureShot.Data.Common.Repositories;
    using NatureShot.Data.Models;
    using NatureShot.Services.Data;
    using NatureShot.Web.CloudinaryHelper;
    using NatureShot.Web.ViewModels;
    using NatureShot.Web.ViewModels.Home;
    using NatureShot.Web.ViewModels.Images;

    public class ImagesController : Controller
    {
        private readonly Cloudinary cloudinary;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IPostsService postsService;
        private readonly ILocationsService locationsService;
        private readonly ICameraService cameraService;
        private readonly ITagsService tagsService;

        public ImagesController(Cloudinary cloudinary,
                                UserManager<ApplicationUser> userManager,
                                IPostsService postsService,
                                ILocationsService locationsService,
                                ICameraService cameraService,
                                ITagsService tagsService)
        {
            this.cloudinary = cloudinary;
            this.postsService = postsService;
            this.userManager = userManager;
            this.locationsService = locationsService;
            this.cameraService = cameraService;
            this.tagsService = tagsService;
        }

        [Authorize]
        public IActionResult AddImage()
        {
            var viewModel = new ImagePostInputModel();
            viewModel.LocationsDropDown = this.locationsService.GetAllLocationsAsKeyValuePair();
            viewModel.CamerasDropDown = this.cameraService.GetAllCamerasAsKeyValuePair();
            viewModel.TagsDropDown = this.tagsService.GetAllTagsAsKeyValuePair();

            return this.View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddImage(ImagePostInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.LocationsDropDown = this.locationsService.GetAllLocationsAsKeyValuePair();
                input.CamerasDropDown = this.cameraService.GetAllCamerasAsKeyValuePair();
                input.TagsDropDown = this.tagsService.GetAllTagsAsKeyValuePair();

                return this.View(input);
            }

            var imageInfo = await CloudinaryExtension.UploadImageAsync(this.cloudinary, input.Image);
            var user = await this.userManager.GetUserAsync(this.User);
            await this.postsService.CreateImagePostAsync(input, user.Id, imageInfo);

            return this.Redirect("/");
        }
    }
}

Nature_Shot/Web/NatureShot.Web/Controllers/NormalPostsController.cs
namespace NatureShot.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using NatureShot.Data.Models;
    using NatureShot.Services.Data;
    using NatureShot.Services.Data.NormalPosts;
    using NatureShot.Web.ViewModels.NormalPosts;
    using NatureShot.Services.Data.Contracts;
    using NatureShot.Services.Data.NormalPosts.Contracts;

    public class NormalPostsController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ITagsService tagsService;
        private readonly IPostsService postsService;
        private readonly INormalPostsNewest normalPostNewestService;
        private readonly INormalPostsOldest normalPostOldestService;
        private readonly INormalPostsMostLikes normalPostMostLikesService;
        private readonly INormalPostsLeastLikes normalPostLeastLikesService;
        private readonly INormalPostsMostDislikes normalPostMostDislikesService;
        private readonly INormalPostsLeastDislikes normalPostLeastDislikesService;

        public NormalPostsController(UserManager<ApplicationUser> userManager,
                                     ITagsService tagsService,
                                     IPostsService postsService,
                                     INormalPostsNewest normalPostNewestService,
                                     INormalPostsOldest normalPostOldestService,
                                     INormalPostsMostLikes normalPostMostLikesService,
                                     INormalPostsLeastLikes normalPostLeastLikesService,
                                     INormalPostsMostDislikes normalPostMostDislikesService,
                                     INormalPostsLeastDislikes normalPostLeastDislikesService)
        {
            this.userManager = userManager;
            this.tagsService = tagsService;
            this.postsService = postsService;
            this.normalPostNewestService = normalPostNewestService;
            this.normalPostOldestService = normalPostOldestService;
            this.normalPostMostLikesService = normalPostMostLikesService;
            this.normalPostLeastLikesService = normalPostLeastLikesService;
            this.normalPostMostDislikesService = normalPostMostDislikesService;
            this.normalPostLeastDislikesService = normalPostLeastDislikesService;
        }

        [Authorize]
        public IActionResult NormalPostsNewest(string searchBy, string searchInput)
        {
            if (searchBy != null && searchInput != null)
            {
                return this.RedirectToAction("SearchByNewest", new { searchBy = searchBy, searchInput = searchInput });
            }

            var viewModel = this.normalPostNewestService.GetNormalPostsNewest(0);
            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult NormalPostsOldest(string searchBy, string searchInput)
        {
            if (searchBy != null && searchInput != null)
            {
                return this.RedirectToAction("SearchByOldest", new { searchBy = searchBy, searchInput = searchInput });
            }

            var viewModel = this.normalPostOldestService.GetNormalPostsOldest(0);
            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult NormalPostsLikesMost(string searchBy, string searchInput)
        {
            if (searchBy != null && searchInput != null)
            {
                return this.RedirectToAction("SearchByMostLikes", new { searchBy = searchBy, searchInput = searchInput });
            }

            var viewModel = this.normalPostMostLikesService.GetNormalPostsMostLikes(0);
            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult NormalPostsLikesLeast(string searchBy, string searchInput)
        {
            if (searchBy != null && searchInput != null)
            {
                return this.RedirectToAction("SearchByLeastLikes", new { searchBy = searchBy, searchInput = searchInput });
            }

            var viewModel = this.normalPostLeastLikesService.GetNormalPostsLeastLikes(0);
            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult NormalPostsDislikesMost(string searchBy, string searchInput)
        {
            if (searchBy != null && searchInput != null)
            {
                return this.RedirectToAction("SearchByMostDislikes", new { searchBy = searchBy, searchInput = searchInput });
            }

            var viewModel = this.normalPostMostDislikesService.GetNormalPostsMostDislikes(0);
            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult NormalPostsDislikesLeast(string searchBy, string searchInput)
        {
            if (searchBy != null && searchInput != null)
            {
                return this.RedirectToAction("SearchByLeastDislikes", new { searchBy = searchBy, searchInput = searchInput });
            }

            var viewModel = this.normalPostLeastDislikesService.GetNormalPostsLeastDislikes(0);
            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult SearchByNewest(string searchBy, string searchInput)
        {
            var viewModel = new List<NormalPostViewModel>();
            switch (searchBy)
            {
                case "Name":
                    viewModel = this.normalPostNewestService.SearchByUsername(0, searchInput).ToList();
                    break;
                case "Tag":
                    viewModel = this.normalPostNewestService.SearchByTags(0, searchInput).ToList();
                    break;
                case "Caption":
                    viewModel = this.normalPostNewestService.SearchByCaption(0, searchInput).ToList();
                    break;
                case "Liked":
                    viewModel = this.normalPostNewestService.SearchByLikedPosts(0, searchInput).ToList();
                    break;
                case "Disliked":
                    viewModel = this.normalPostNewestService.SearchByDislikedPosts(0, searchInput).ToList();
                    break;
                case "Commented":
                    viewModel = this.normalPostNewestService.SearchByCommentedPosts(0, searchInput).ToList();
                    break;
                default:
                    break;
            }

            return this.View("NormalPostsNewest", viewModel);
        }

        [Authorize]
        public IActionResult SearchByOldest(string searchBy, string searchInput)
        {
            var viewModel = new List<NormalPostViewModel>();
            switch (searchBy)
            {
                case "Name":
                    viewModel = this.normalPostOldestService.SearchByUsername(0, searchInput).ToList();
                    break;
                case "Tag":
                    viewModel = this.normalPostOldestService.SearchByTags(0, searchInput).ToList();
                    break;
                case "Caption":
                    viewModel = this.normalPostOldestService.SearchByCaption(0, searchInput).ToList();
                    break;
                case "Liked":
                    viewModel = this.normalPostOldestService.SearchByLikedPosts(0, searchInput).ToList();
                    break;
                case "Disliked":
                    viewModel = this.normalPostOldestService.SearchByDislikedPosts(0, searchInput).ToList();
                    break;
                case "Commented":
                    viewModel = this.normalPostOldestService.SearchByCommentedPosts(0, searchInput).ToList();
                    break;
                default:
                    break;
            }

            return this.View("NormalPostsOldest", viewModel);
        }

        [Authorize]
        public IActionResult SearchByMostLikes(string searchBy, string searchInput)
        {
            var viewModel = new List<NormalPostViewModel>();
            switch (searchBy)
            {
                case "Name":
                    viewModel = this.normalPostMostLikesService.SearchByUsername(0, searchInput).ToList();
                    break;
                case "Tag":
                    viewModel = this.normalPostMostLikesService.SearchByTags(0, searchInput).ToList();
                    break;
                case "Caption":
                    viewModel = this.normalPostMostLikesService.SearchByCaption(0, searchInput).ToList();
                    break;
                case "Liked":
                    viewModel = this.normalPostMostLikesService.SearchByLikedPosts(0, searchInput).ToList();
                    break;
                case "Disliked":
                    viewModel = this.normalPostMostLikesService.SearchByDislikedPosts(0, searchInput).ToList();
                    break;
                case "Commented":
                    viewModel = this.normalPostMostLikesService.SearchByCommentedPosts(0, searchInput).ToList();
                    break;
                default:
                    break;
            }

            return this.View("NormalPostsLikesMost", viewModel);
        }

        [Authorize]
        public IActionResult SearchByLeastLikes(string searchBy, string searchInput)
        {
            var viewModel = new List<NormalPostViewModel>();
            switch (searchBy)
            {
                case "Name":
                    viewModel = this.normalPostLeastLikesService.SearchByUsername(0, searchInput).ToList();
                    break;
                case "Tag":
                    viewModel = this.normalPostLeastLikesService.SearchByTags(0, searchInput).ToList();
                    break;
                case "Caption":

Nature_Shot/Web/NatureShot.Web/Views/Images/AddImage.cshtml
@model NatureShot.Web.ViewModels.Images.ImagePostInputModel
@{
    this.ViewData["Title"] = "Share Image";
    var locationItems = Model.LocationsDropDown.Select(x => new SelectListItem(x.Value, x.Key));
    var cameraItems = Model.CamerasDropDown.Select(x => new SelectListItem(x.Value, x.Key));
    var tagItems = Model.TagsDropDown.Select(x => new SelectListItem(x.Value, x.Key));
}

<a asp-controller="NormalPosts" asp-action="AddPost" class="btn btn-primary mb-2 mr-2 m text-white">Go Share Post</a>
<a class="btn btn-primary mb-2 text-white">Go Share Video</a>

<div class="row justify-content-center no-gutters mb-5 border border-primary round">
    <div class="text-center h-100 project">
        <div class="d-flex h-100">
            <div class="project-text w-100 my-auto text-center">
                <form method="post" enctype="multipart/form-data" asp-controller="Images" asp-action="AddImage">
                    <div class="text-center">

                        <!--USER NAME-->
                        <h4>@this.User.Identity.Name</h4>

                        <div asp-validation-summary="All" class="text-danger"></div>
                        <br>

                        <!--IMAGE FILE INPUT-->
                        <div class="input-group">
                            <div class="custom-file">
                                <input asp-for="Image" id="fileInput" type="file" accept="image/*" class="custom-file-input form-control" />
                                <label asp-for="Image" id="fileLabel" class="custom-file-label text-black-50 mb-1 border border-primary rounded">Select <span class="text-dark text-uppercase">Image</span></label>
                            </div>
                        </div>
                        <span asp-validation-for="Image" class="text-danger"></span>

                        <br>

                        <!--TAGS INPUT-->
                        <label asp-for="Tags" class="text-black-50 mb-1"><u>Type some <span class="text-dark text-uppercase">#tags</span> here:</u></label>
                        <div class="input-group-lg input-group">
                            <textarea asp-for="Tags" id="tagInput" type="text" class="form-control col-12 mt-2 border border-primary rounded-left" aria-label="Text input with dropdown button" rows="1"></textarea>
                            <div class="input-group-append col-12">
                                <select asp-items="tagItems" id="tagSelect" data-live-search="true" data-live-search-placeholder="Search Location" class="form-control selectpicker border border-primary rounded" multiple data-selected-text-format="count > 1" data-size="6">
                                    @*<option>No Camera...</option>
                                        <option>#day</option>
                                        <option>#hot</option>
                                        <option>#beautiful</option>
                                        <option>#wow</option>
                                        <option>#love</option>
                                        <option>#moon</option>
                                        <option>#sun</option>
                                        <option>#night</option>*@
                                </select>
                            </div>
                        </div>
                        <span asp-validation-for="Tags" class="text-danger"></span>
                        <br>

                        <!--CAPTION INPUT-->
                        <div class="form-group">
                            <label asp-for="Caption" class="text-black-50 mb-1"><u>Write short <span class="text-dark text-uppercase">description/caption</span> here:</u></label>
                            <textarea asp-for="Caption" type="text" class="form-control border border-primary rounded" placeholder="Very beautiful and breath taking, place i recomment you to go there!" rows="5"></textarea>
                            <span asp-validation-for="Caption" class="text-danger"></span>
                        </div>

                        <br>

                        <!--LOCATION INPUT-->
                        <label asp-for="Location" class="text-black-50 mb-1"><u>Select <span class="text-dark text-uppercase">Location</span> where you took the photo:</u></label>
                        <div class="input-group-lg input-group">
                            <input asp-for="Location" id="townInput" type="text" class="form-control col-6 mt-2 border border-primary rounded-left" aria-label="Text input with dropdown button">
                            <input asp-for="Country" id="countryInput" type="text" class="form-control col-6 mt-2 border border-primary rounded-right" aria-label="Text input with dropdown button">
                        </div>
                        <div class="border border-primary rounded">
                            <select asp-items="locationItems" id="locationDropDown" data-live-search="true" data-live-search-placeholder="Search Location" class="form-control selectpicker" data-size="6">
                                @*<option>No Camera...</option>
                                    <option>Plovdiv/Bulgaria</option>
                                    <option>Burgas/Bulgaria</option>
                                    <option>Varna/Bulgaria</option>
                                    <option>Sofia/Bulgaria</option>
                                    <option>Pazarzdik/Bulgaria</option>
                                    <option>Peshtera/Bulgaria</option>
                                    <option>Stara Zagora/Bulgaria</option>
                                    <option>Rila/Bulgaria</option>*@
                            </select>
                        </div>
                        <span asp-validation-for="Location" class="text-danger"></span>
                        <br>
                        <span asp-validation-for="Country" class="text-danger"></span>

                        <br>
                        <br>

                        <!--CAMERA INPUT-->
                        <label asp-for="Camera" class="text-black-50 mb-1"><u>Select the <span class="text-dark text-uppercase">Camera</span> which took the photo:</u></label>
                        <div class="input-group-lg input-group">
                            <input asp-for="Camera" id="cameraInput" type="text" class="form-control col-6 mt-2 border border-primary rounded-left" aria-label="Text input with dropdown button">
                            <div class="input-group-append col-6">
                                <select asp-items="cameraItems" id="cameraSelect" data-live-search="true" data-live-search-placeholder="Search Location" class="form-control selectpicker border border-primary rounded" data-size="6">
                                    @*<option selected>No Camera...</option>
                                        <option>Plovdiv/Bulgaria</option>
                                        <option>Orange</option>
                                        <option>Lychee</option>
                                        <option>Pineapple</option>
                                        <option>Apple</option>
                                        <option>Banana</option>
                                        <option>Grapes</option>
                                        <option>Water Melon</option>*@
                                </select>
                            </div>
                        </div>
                        <span asp-validation-for="Camera" class="text-danger"></span>

                    </div>
                    <div class="text-center">
                        <button type="submit" value="AddImage" class="btn btn-outline-primary mt-4 border border-primary rounded" name="uploadbutton">Share Image</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script src="~/js/SelectFields.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
}