Nature_Shot/Web/NatureShot.Web/Areas/Administration/Controllers/TagsController.cs
namespace NatureShot.Web.Areas.Administration.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using NatureShot.Data;
    using NatureShot.Data.Common.Repositories;
    using NatureShot.Data.Models;

    public class TagsController : AdministrationController
    {
        private readonly IDeletableEntityRepository<Tag> tagRepository;

        public TagsController(IDeletableEntityRepository<Tag> tagRepository)
        {
            this.tagRepository = tagRepository;
        }

        // GET: Tags
        public async Task<IActionResult> Index()
        {
            return this.View(await this.tagRepository.AllWithDeleted().ToListAsync());
        }

        // GET: Tags/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var tag = await this.tagRepository.AllWithDeleted()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tag == null)
            {
                return this.NotFound();
            }

            return this.View(tag);
        }

        // GET: Tags/Create
        public IActionResult Create()
        {
            return this.View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Tag tag)
        {
            if (this.ModelState.IsValid)
            {
                await this.tagRepository.AddAsync(tag);
                await this.tagRepository.SaveChangesAsync();
                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(tag);
        }

        // GET: Tags/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var tag = this.tagRepository.AllWithDeleted().FirstOrDefault(x => x.Id == id);
            if (tag == null)
            {
                return this.NotFound();
            }

            return this.View(tag);
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Tag tag)
        {
            if (id != tag.Id)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    this.tagRepository.Update(tag);
                    await this.tagRepository.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.TagExists(tag.Id))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(tag);
        }

        // GET: Tags/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var tag = await this.tagRepository.AllWithDeleted()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tag == null)
            {
                return this.NotFound();
            }

            return this.View(tag);
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tag = this.tagRepository.AllWithDeleted().FirstOrDefault(x => x.Id == id);
            this.tagRepository.Delete(tag);
            await this.tagRepository.SaveChangesAsync();
            return this.RedirectToAction(nameof(this.Index));
        }

        private bool TagExists(int id)
        {
            return this.tagRepository.AllWithDeleted().Any(e => e.Id == id);
        }
    }
}

Nature_Shot/Web/NatureShot.Web/Controllers/ChatController.cs
namespace NatureShot.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using NatureShot.Services.Data.Contracts;

    public class ChatController : Controller
    {
        private readonly IChatService chatService;

        public ChatController(IChatService chatService)
        {
            this.chatService = chatService;
        }

        [Authorize]
        public IActionResult Messaging()
        {
            return this.View();
        }

        [Authorize]
        public IActionResult MyChats()
        {
            var chats = this.chatService.GetUserChats(this.User.Identity.Name);
            return this.View(chats);
        }

        [Authorize]
        public IActionResult SearchByUsername(string searchInput)
        {
            var chats = this.chatService.SearchByUsername(this.User.Identity.Name, searchInput);
            return this.View(nameof(this.MyChats), chats);
        }

        [Authorize]
        public async Task<IActionResult> OpenChat(string username)
        {
            var firstUsername = this.User.Identity.Name;
            var groupName = this.chatService.CheckGroupExists(firstUsername, username);
            if (groupName == null)
            {
                await this.chatService.CreateGroup(firstUsername, username);
                await this.chatService.AddToGroup(firstUsername, username);
            }

            var viewModel = await this.chatService.GetMessagesForChat(firstUsername, username);

            return this.View(viewModel);
        }
    }
}

Nature_Shot/Web/NatureShot.Web/Controllers/PostsController.cs
namespace NatureShot.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using CloudinaryDotNet;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using NatureShot.Data.Models;
    using NatureShot.Services.Data;
    using NatureShot.Web.CloudinaryHelper;
    using NatureShot.Web.ViewModels.Images;
    using NatureShot.Web.ViewModels.NormalPosts;
    using NatureShot.Web.ViewModels.Videos;
    using NatureShot.Services.Data.Contracts;

    public class PostsController : Controller
    {
        private Cloudinary cloudinary;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IPostsService postsService;
        private readonly ILocationsService locationsService;
        private readonly ICameraService cameraService;
        private readonly ITagsService tagsService;

        public PostsController(Cloudinary cloudinary,
                                UserManager<ApplicationUser> userManager,
                                IPostsService postsService,
                                ILocationsService locationsService,
                                ICameraService cameraService,
                                ITagsService tagsService)
        {
            this.cloudinary = cloudinary;
            this.userManager = userManager;
            this.postsService = postsService;
            this.locationsService = locationsService;
            this.cameraService = cameraService;
            this.tagsService = tagsService;
        }

        [Authorize]
        public IActionResult AddImage()
        {
            var viewModel = new ImagePostInputModel();
            viewModel.LocationsDropDown = this.locationsService.GetAllLocationsAsKeyValuePair();
            viewModel.CamerasDropDown = this.cameraService.GetAllCamerasAsKeyValuePair();
            viewModel.TagsDropDown = this.tagsService.GetAllTagsAsKeyValuePair();

            return this.View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddImage(ImagePostInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.LocationsDropDown = this.locationsService.GetAllLocationsAsKeyValuePair();
                input.CamerasDropDown = this.cameraService.GetAllCamerasAsKeyValuePair();
                input.TagsDropDown = this.tagsService.GetAllTagsAsKeyValuePair();

                return this.View(input);
            }

            var imageInfo = await CloudinaryExtension.UploadImageAsync(this.cloudinary, input.Image);
            var user = await this.userManager.GetUserAsync(this.User);
            await this.postsService.CreateImagePostAsync(input, user.Id, imageInfo);

            return this.Redirect("/");
        }

        [Authorize]
        public IActionResult AddPost()
        {
            var viewModel = new NormalPostInputModel();
            viewModel.TagsDropDown = this.tagsService.GetAllTagsAsKeyValuePair();
            return this.View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddPost(NormalPostInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.TagsDropDown = this.tagsService.GetAllTagsAsKeyValuePair();

                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            await this.postsService.CreateNormalPostAsync(input, user.Id);

            return this.Redirect("/");
        }

        [Authorize]
        public IActionResult AddVideo()
        {
            var viewModel = new VideoPostInputModel();
            viewModel.LocationsDropDown = this.locationsService.GetAllLocationsAsKeyValuePair();
            viewModel.CamerasDropDown = this.cameraService.GetAllCamerasAsKeyValuePair();
            viewModel.TagsDropDown = this.tagsService.GetAllTagsAsKeyValuePair();

            return this.View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddVideo(VideoPostInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.LocationsDropDown = this.locationsService.GetAllLocationsAsKeyValuePair();
                input.CamerasDropDown = this.cameraService.GetAllCamerasAsKeyValuePair();
                input.TagsDropDown = this.tagsService.GetAllTagsAsKeyValuePair();

                return this.View(input);
            }

            var videoInfo = await CloudinaryExtension.UploadVideoAsync(this.cloudinary, input.Video);
            var user = await this.userManager.GetUserAsync(this.User);
            await this.postsService.CreateVideoPostAsync(input, user.Id, videoInfo);

            return this.Redirect("/");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> DeleteImage(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            if (!this.postsService.CheckPostOwner(id, user.Id))
            {
                return this.Redirect($"/PhotoPosts/PhotosNewest");
            }

            await this.postsService.Delete(id);
            return this.Redirect($"/PhotoPosts/PhotosNewest");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> DeleteVideo(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            if (!this.postsService.CheckPostOwner(id, user.Id))
            {
                return this.Redirect("/VideoPosts/VideosNewest");
            }

            await this.postsService.Delete(id);
            return this.Redirect("/VideoPosts/VideosNewest");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> DeletePost(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            if (!this.postsService.CheckPostOwner(id, user.Id))
            {
                return this.Redirect("/NormalPosts/NormalPostsNewest");
            }

            await this.postsService.Delete(id);
            return this.Redirect("/NormalPosts/NormalPostsNewest");
        }

        [Authorize]
        public async Task<IActionResult> UpdateImage(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            if (!this.postsService.CheckPostOwner(id, user.Id))
            {
                return this.Redirect($"/PhotoPosts/PhotosNewest");
            }

            var viewModel = this.postsService.GetImagePost(id);
            viewModel.LocationsDropDown = this.locationsService.GetAllLocationsAsKeyValuePair();
            viewModel.CamerasDropDown = this.cameraService.GetAllCamerasAsKeyValuePair();
            viewModel.TagsDropDown = this.tagsService.GetAllTagsAsKeyValuePair();
            return this.View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> UpdateVideo(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            if (!this.postsService.CheckPostOwner(id, user.Id))
            {
                return this.Redirect("/VideoPosts/VideosNewest");
            }

            var viewModel = this.postsService.GetVideoPost(id);
            viewModel.LocationsDropDown = this.locationsService.GetAllLocationsAsKeyValuePair();
            viewModel.CamerasDropDown = this.cameraService.GetAllCamerasAsKeyValuePair();
            viewModel.TagsDropDown = this.tagsService.GetAllTagsAsKeyValuePair();
            return this.View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> UpdatePost(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            if (!this.postsService.CheckPostOwner(id, user.Id))
            {
                return this.Redirect("/NormalPosts/NormalPostsNewest");
            }

            var viewModel = this.postsService.GetNormalPost(id);
            viewModel.TagsDropDown = this.tagsService.GetAllTagsAsKeyValuePair();
            return this.View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> UpdateVideo(VideoPostUpdateModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.LocationsDropDown = this.locationsService.GetAllLocationsAsKeyValuePair();
                input.CamerasDropDown = this.cameraService.GetAllCamerasAsKeyValuePair();
                input.TagsDropDown = this.tagsService.GetAllTagsAsKeyValuePair();

                return this.View(input);
            }

            await this.postsService.UpdateVideo(input);
            return this.Redirect("/VideoPosts/VideosNewest");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> UpdateImage(ImagePostUpdateModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.LocationsDropDown = this.locationsService.GetAllLocationsAsKeyValuePair();
                input.CamerasDropDown = this.cameraService.GetAllCamerasAsKeyValuePair();
                input.TagsDropDown = this.tagsService.GetAllTagsAsKeyValuePair();

                return this.View(input);
            }

            await this.postsService.UpdateImage(input);
            return this.Redirect($"/PhotoPosts/PhotosNewest");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> UpdatePost(NormalPostUpdateModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.TagsDropDown = this.tagsService.GetAllTagsAsKeyValuePair();

                return this.View(input);
            }

            await this.postsService.UpdatePost(input);
            return this.Redirect("/NormalPosts/NormalPostsNewest");
        }
    }
}

Nature_Shot/Web/NatureShot.Web/Views/Shared/_Layout.cshtml
@using NatureShot.Common

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
</head>
<body id="page-top">

    <header>
        @if ((string)this.ViewData["Action"] == "Index")
        {
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-tree"></i> Nature Shot</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="https://github.com/DimitarKazakov/NatureShotWebSite/blob/main/README.md">About</a></li>
                <partial name="_LoginPartial" />
            </ul>
        </div>
    </div>
</nav> }
else
{
<nav class="navbar navbar-expand-lg navbar-light fixed-top border-bottom border-primary" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-tree text-primary"></i> Nature Shot</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto" id="navHover">
                <hr class="d-none d-lg-block mb-0 ml-0" />
                @if (this.User.Identity.IsAuthenticated)
                {
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownChat" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="line">Chat</span>
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownChat">
        <a class="dropdown-item" asp-area="" asp-controller="Chat" asp-action="MyChats"><span class="line">My Chats</span></a>
        <a class="dropdown-item" asp-area="" asp-controller="Chat" asp-action="Messaging"><span class="line">Just Chatting</span></a>
    </div>
</li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="line">Share</span>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown3">
                            <a class="dropdown-item" asp-area="" asp-controller="Posts" asp-action="AddImage"><span class="line">Image</span></a>
                            <a class="dropdown-item" asp-area="" asp-controller="Posts" asp-action="AddVideo"><span class="line">Video</span></a>
                            <a class="dropdown-item" asp-area="" asp-controller="Posts" asp-action="AddPost"><span class="line">Post</span></a>
                        </div>
                    </li>
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <span class="line">User Shares</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                                                <a class="dropdown-item" asp-area="" asp-controller="NormalPosts" asp-action="NormalPostsNewest"><span class="line">Posts</span></a>
                                                <a class="dropdown-item" asp-area="" asp-controller="PhotoPosts" asp-action="PhotosNewest"><span class="line">Photos</span></a>
                                                <a class="dropdown-item" asp-area="" asp-controller="VideoPosts" asp-action="VideosNewest"><span class="line">Videos</span></a>
                                            </div>
                                        </li>
                                                            @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                                                            {
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownAdmin" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <span class="line">Administration</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="navbarDropdownAdmin">
                                                <a class="dropdown-item" asp-area="Administration" asp-controller="Tags" asp-action="Index"><span class="line">Tags</span></a>
                                                <a class="dropdown-item" asp-area="Administration" asp-controller="Countries" asp-action="Index"><span class="line">Countries</span></a>
                                                <a class="dropdown-item" asp-area="Administration" asp-controller="Locations" asp-action="Index"><span class="line">Locations</span></a>
                                                <a class="dropdown-item" asp-area="Administration" asp-controller="ApplicationUsers" asp-action="Index"><span class="line">Users</span></a>
                                                <a class="dropdown-item" asp-area="Administration" asp-controller="Cameras" asp-action="Index"><span class="line">Cameras</span></a>
                                                <a class="dropdown-item" asp-area="Administration" asp-controller="Comments" asp-action="Index"><span class="line">Comments</span></a>
                                                <a class="dropdown-item" asp-area="Administration" asp-controller="Reports" asp-action="Index"><span class="line">Reports</span></a>
                                            </div>
                                        </li>}}
                                                        else
                                                        {
                                        <li class="nav-item"><a class="nav-link js-scroll-trigger text-dark" href="https://github.com/DimitarKazakov/NatureShotWebSite/blob/main/README.md">About</a></li>
}
                <partial name="_LoginPartial" />
            </ul>
            <div class="line"></div>
        </div>
    </div>
</nav>}
    </header>

    @if ((string)this.ViewData["Action"] == "Index")
    {
@this.RenderBody() }
else
{
<section class="projects-section bg-light" id="projects">
    <div class="container shadow p-4 rounded" id="photosClick">
        <partial name="_CookieConsentPartial" />
        @this.RenderBody()
    </div>
</section>}

    <footer class="page-footer font-small stylish-color-dark pt-4 row text-center">

        <!-- Social buttons -->
        <ul class="list-unstyled list-inline text-center col-12 pt-4">
            <li class="list-inline-item">
                <a class="btn-floating btn-fb mx-1">
                    <i class="fab fa-facebook-f"> </i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="btn-floating btn-tw mx-1">
                    <i class="fab fa-twitter"> </i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="btn-floating btn-gplus mx-1">
                    <i class="fab fa-instagram"> </i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="btn-floating btn-gplus mx-1">
                    <i class="fab fa-pinterest"> </i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="btn-floating btn-li mx-1">
                    <i class="fab fa-linkedin-in"> </i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="btn-floating btn-dribbble mx-1" href="https://github.com/DimitarKazakov/NatureShotWebSite">
                    <i class="fab fa-github"></i>
                </a>
            </li>
        </ul>
        <!-- Social buttons -->
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3 col-12 border-bottom border-secondary pb-4">
            © @DateTime.Now.Year Copyright:
            <a href="#"> Nature Shot</a>
        </div>
        <!-- Copyright -->

    </footer>

    @*
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>*@

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src="~/lib/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>